import { Amplify } from 'aws-amplify';
import outputs from '@/amplify_outputs.json';
import '@aws-amplify/ui-react/styles.css';
import '@/styles/globals.css';
import { generateClient } from "aws-amplify/data";
import type { Schema } from "@/data-schema";
import { useEffect, useState } from 'react';
import { Authenticator} from '@aws-amplify/ui-react';
import "./app.css"
import type { AppProps } from 'next/app';
// import { withAuthenticator } from '@aws-amplify/ui-react';

Amplify.configure(outputs);
const client = generateClient<Schema>();


function App({}: AppProps) {
  // return <Component {...pageProps} />;
    // configure the Amplify client library with the configuration generated by `ampx sandbox`
    // const { signOut, user } = useAuthenticator();
    const [todos, setTodos] = useState<Array<Schema["Todo"]["type"]>>([]);

    function listTodos() {
      client.models.Todo.observeQuery().subscribe({
        next: (data) => setTodos([...data.items]),
      });
    }

    useEffect(() => {
      listTodos();
    }, []);

    function createTodo() {
      client.models.Todo.create({
        content: window.prompt("Todo content"),
      });
    }

    function deleteTodo(id: string){
      client.models.Todo.delete({id});
    } 

    return (
      <Authenticator>
       {({ signOut, user }) => (
          <main>
            <h1>{user?.signInDetails?.loginId}`&apos;`s todos</h1>
            <button onClick={createTodo}>+ new</button>
            <ul>
              {todos.map((todo) => (
                <li onClick={()=>deleteTodo(todo.id)} key={todo.id}>{todo.content}</li>
              ))}
            </ul>
            <div>
              🥳 App successfully hosted. Try creating a new todo.
              <br />
              <a href="https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/">
                Review next steps of this tutorial.
              </a>
            </div>

            <button onClick={signOut}>Sign out</button>
          </main>
        )}
      </Authenticator>
  );
}

export default App;
// export default withAuthenticator(App);

// export default function App() {
//   const [todos, setTodos] = useState<Array<Schema["Todo"]["type"]>>([]);

//   function listTodos() {
//     client.models.Todo.observeQuery().subscribe({
//       next: (data) => setTodos([...data.items]),
//     });
//   }

//   useEffect(() => {
//     listTodos();
//   }, []);

//   function createTodo() {
//     client.models.Todo.create({
//       content: window.prompt("Todo content"),
//     });
//   }

//   function deleteTodo(id: string){
//     client.models.Todo.delete({id});
//   } 
  
//   return (
//     <Authenticator>
//       {({ signOut, user }) => (
//       <main>
//         <h1>{user?.signInDetails?.loginId}`&apos;`s todos</h1>
//         <button onClick={createTodo}>+ new</button>
//         <ul>
//           {todos.map((todo) => (
//             <li onClick={()=>deleteTodo(todo.id)} key={todo.id}>{todo.content}</li>
//           ))}
//         </ul>
//         <div>
//           🥳 App successfully hosted. Try creating a new todo.
//           <br />
//           <a href="https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/">
//             Review next steps of this tutorial.
//           </a>
//         </div>

//         <button onClick={signOut}>Sign out</button>
//       </main>
//     )}
//     </Authenticator>
//   );
// }